DROP INDEX IF EXISTS idx_mg_approvals_turn_id;

ALTER TABLE MGApprovals DROP COLUMN IF EXISTS ExpiresAt;
ALTER TABLE MGApprovals DROP COLUMN IF EXISTS TurnId;

ALTER TABLE MGTurns DROP COLUMN IF EXISTS RunId;
ALTER TABLE MGTurns DROP COLUMN IF EXISTS Model;
ALTER TABLE MGTurns DROP COLUMN IF EXISTS Provider;

ALTER TABLE MGAgentProfiles DROP COLUMN IF EXISTS Runtime;
