DROP TABLE IF EXISTS MGMarkdownExports;
DROP TABLE IF EXISTS MGMemoryProposals;
DROP TABLE IF EXISTS MGApprovals;
DROP TABLE IF EXISTS MGTurns;
DROP TABLE IF EXISTS MGSessionParticipants;
DROP TABLE IF EXISTS MGSessions;
DROP TABLE IF EXISTS MGAgentProfiles;
