// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

// Code generated by "make store-layers"
// DO NOT EDIT
//
// MatterGoat store retry layer. Hand-authored to mirror generated output;
// `make store-layers` will canonicalize this file.

package retrylayer

import (
	timepkg "time"

	"github.com/mattermost/mattermost/server/public/model"
	"github.com/mattermost/mattermost/server/v8/channels/store"
	"github.com/pkg/errors"
)

type RetryLayerMatterGoatStore struct {
	store.MatterGoatStore
	Root *RetryLayer
}

func (s *RetryLayer) MatterGoat() store.MatterGoatStore {
	return s.MatterGoatStore
}

func mgRetry[T any](fn func() (T, error)) (T, error) {
	tries := 0
	for {
		result, err := fn()
		if err == nil {
			return result, nil
		}
		if !isRepeatableError(err) {
			return result, err
		}
		tries++
		if tries >= 3 {
			err = errors.Wrap(err, "giving up after 3 consecutive repeatable transaction failures")
			return result, err
		}
		timepkg.Sleep(100 * timepkg.Millisecond)
	}
}

func mgRetryErr(fn func() error) error {
	_, err := mgRetry(func() (struct{}, error) {
		return struct{}{}, fn()
	})
	return err
}

func (s *RetryLayerMatterGoatStore) SaveAgentProfile(profile *model.MGAgentProfile) (*model.MGAgentProfile, error) {
	return mgRetry(func() (*model.MGAgentProfile, error) { return s.MatterGoatStore.SaveAgentProfile(profile) })
}

func (s *RetryLayerMatterGoatStore) UpdateAgentProfile(profile *model.MGAgentProfile) (*model.MGAgentProfile, error) {
	return mgRetry(func() (*model.MGAgentProfile, error) { return s.MatterGoatStore.UpdateAgentProfile(profile) })
}

func (s *RetryLayerMatterGoatStore) GetAgentProfile(id string) (*model.MGAgentProfile, error) {
	return mgRetry(func() (*model.MGAgentProfile, error) { return s.MatterGoatStore.GetAgentProfile(id) })
}

func (s *RetryLayerMatterGoatStore) GetAgentProfilesByOwner(ownerType string, ownerId string) ([]*model.MGAgentProfile, error) {
	return mgRetry(func() ([]*model.MGAgentProfile, error) { return s.MatterGoatStore.GetAgentProfilesByOwner(ownerType, ownerId) })
}

func (s *RetryLayerMatterGoatStore) DeleteAgentProfile(id string) error {
	return mgRetryErr(func() error { return s.MatterGoatStore.DeleteAgentProfile(id) })
}

func (s *RetryLayerMatterGoatStore) SaveSession(session *model.MGSession) (*model.MGSession, error) {
	return mgRetry(func() (*model.MGSession, error) { return s.MatterGoatStore.SaveSession(session) })
}

func (s *RetryLayerMatterGoatStore) UpdateSession(session *model.MGSession) (*model.MGSession, error) {
	return mgRetry(func() (*model.MGSession, error) { return s.MatterGoatStore.UpdateSession(session) })
}

func (s *RetryLayerMatterGoatStore) GetSession(id string) (*model.MGSession, error) {
	return mgRetry(func() (*model.MGSession, error) { return s.MatterGoatStore.GetSession(id) })
}

func (s *RetryLayerMatterGoatStore) GetSessionsForChannel(channelId string) ([]*model.MGSession, error) {
	return mgRetry(func() ([]*model.MGSession, error) { return s.MatterGoatStore.GetSessionsForChannel(channelId) })
}

func (s *RetryLayerMatterGoatStore) DeleteSession(id string) error {
	return mgRetryErr(func() error { return s.MatterGoatStore.DeleteSession(id) })
}

func (s *RetryLayerMatterGoatStore) SaveParticipant(participant *model.MGSessionParticipant) (*model.MGSessionParticipant, error) {
	return mgRetry(func() (*model.MGSessionParticipant, error) { return s.MatterGoatStore.SaveParticipant(participant) })
}

func (s *RetryLayerMatterGoatStore) GetParticipantsForSession(sessionId string) ([]*model.MGSessionParticipant, error) {
	return mgRetry(func() ([]*model.MGSessionParticipant, error) { return s.MatterGoatStore.GetParticipantsForSession(sessionId) })
}

func (s *RetryLayerMatterGoatStore) DeleteParticipant(sessionId string, agentProfileId string) error {
	return mgRetryErr(func() error { return s.MatterGoatStore.DeleteParticipant(sessionId, agentProfileId) })
}

func (s *RetryLayerMatterGoatStore) SaveTurn(turn *model.MGTurn) (*model.MGTurn, error) {
	return mgRetry(func() (*model.MGTurn, error) { return s.MatterGoatStore.SaveTurn(turn) })
}

func (s *RetryLayerMatterGoatStore) UpdateTurn(turn *model.MGTurn) (*model.MGTurn, error) {
	return mgRetry(func() (*model.MGTurn, error) { return s.MatterGoatStore.UpdateTurn(turn) })
}

func (s *RetryLayerMatterGoatStore) GetTurnsForSession(sessionId string) ([]*model.MGTurn, error) {
	return mgRetry(func() ([]*model.MGTurn, error) { return s.MatterGoatStore.GetTurnsForSession(sessionId) })
}

func (s *RetryLayerMatterGoatStore) SaveApproval(approval *model.MGApproval) (*model.MGApproval, error) {
	return mgRetry(func() (*model.MGApproval, error) { return s.MatterGoatStore.SaveApproval(approval) })
}

func (s *RetryLayerMatterGoatStore) UpdateApproval(approval *model.MGApproval) (*model.MGApproval, error) {
	return mgRetry(func() (*model.MGApproval, error) { return s.MatterGoatStore.UpdateApproval(approval) })
}

func (s *RetryLayerMatterGoatStore) GetApproval(id string) (*model.MGApproval, error) {
	return mgRetry(func() (*model.MGApproval, error) { return s.MatterGoatStore.GetApproval(id) })
}

func (s *RetryLayerMatterGoatStore) GetApprovalsForSession(sessionId string) ([]*model.MGApproval, error) {
	return mgRetry(func() ([]*model.MGApproval, error) { return s.MatterGoatStore.GetApprovalsForSession(sessionId) })
}

func (s *RetryLayerMatterGoatStore) SaveMemoryProposal(proposal *model.MGMemoryProposal) (*model.MGMemoryProposal, error) {
	return mgRetry(func() (*model.MGMemoryProposal, error) { return s.MatterGoatStore.SaveMemoryProposal(proposal) })
}

func (s *RetryLayerMatterGoatStore) UpdateMemoryProposal(proposal *model.MGMemoryProposal) (*model.MGMemoryProposal, error) {
	return mgRetry(func() (*model.MGMemoryProposal, error) { return s.MatterGoatStore.UpdateMemoryProposal(proposal) })
}

func (s *RetryLayerMatterGoatStore) GetMemoryProposalsForSession(sessionId string) ([]*model.MGMemoryProposal, error) {
	return mgRetry(func() ([]*model.MGMemoryProposal, error) { return s.MatterGoatStore.GetMemoryProposalsForSession(sessionId) })
}

func (s *RetryLayerMatterGoatStore) SaveMarkdownExport(export *model.MGMarkdownExport) (*model.MGMarkdownExport, error) {
	return mgRetry(func() (*model.MGMarkdownExport, error) { return s.MatterGoatStore.SaveMarkdownExport(export) })
}

func (s *RetryLayerMatterGoatStore) GetMarkdownExportsForSession(sessionId string) ([]*model.MGMarkdownExport, error) {
	return mgRetry(func() ([]*model.MGMarkdownExport, error) { return s.MatterGoatStore.GetMarkdownExportsForSession(sessionId) })
}
