// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

// Code generated by "make store-layers"
// DO NOT EDIT
//
// MatterGoat store timer layer. Hand-authored to mirror generated output;
// `make store-layers` will canonicalize this file.

package timerlayer

import (
	"time"

	"github.com/mattermost/mattermost/server/public/model"
	"github.com/mattermost/mattermost/server/v8/channels/store"
)

type TimerLayerMatterGoatStore struct {
	store.MatterGoatStore
	Root *TimerLayer
}

func (s *TimerLayer) MatterGoat() store.MatterGoatStore {
	return s.MatterGoatStore
}

func (s *TimerLayerMatterGoatStore) observe(method string, start time.Time, err error) {
	elapsed := float64(time.Since(start)) / float64(time.Second)
	if s.Root.Metrics != nil {
		success := "false"
		if err == nil {
			success = "true"
		}
		s.Root.Metrics.ObserveStoreMethodDuration("MatterGoatStore."+method, success, elapsed)
	}
}

func (s *TimerLayerMatterGoatStore) SaveAgentProfile(profile *model.MGAgentProfile) (*model.MGAgentProfile, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.SaveAgentProfile(profile)
	s.observe("SaveAgentProfile", start, err)
	return result, err
}

func (s *TimerLayerMatterGoatStore) UpdateAgentProfile(profile *model.MGAgentProfile) (*model.MGAgentProfile, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.UpdateAgentProfile(profile)
	s.observe("UpdateAgentProfile", start, err)
	return result, err
}

func (s *TimerLayerMatterGoatStore) GetAgentProfile(id string) (*model.MGAgentProfile, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.GetAgentProfile(id)
	s.observe("GetAgentProfile", start, err)
	return result, err
}

func (s *TimerLayerMatterGoatStore) GetAgentProfilesByOwner(ownerType string, ownerId string) ([]*model.MGAgentProfile, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.GetAgentProfilesByOwner(ownerType, ownerId)
	s.observe("GetAgentProfilesByOwner", start, err)
	return result, err
}

func (s *TimerLayerMatterGoatStore) DeleteAgentProfile(id string) error {
	start := time.Now()
	err := s.MatterGoatStore.DeleteAgentProfile(id)
	s.observe("DeleteAgentProfile", start, err)
	return err
}

func (s *TimerLayerMatterGoatStore) SaveSession(session *model.MGSession) (*model.MGSession, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.SaveSession(session)
	s.observe("SaveSession", start, err)
	return result, err
}

func (s *TimerLayerMatterGoatStore) UpdateSession(session *model.MGSession) (*model.MGSession, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.UpdateSession(session)
	s.observe("UpdateSession", start, err)
	return result, err
}

func (s *TimerLayerMatterGoatStore) GetSession(id string) (*model.MGSession, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.GetSession(id)
	s.observe("GetSession", start, err)
	return result, err
}

func (s *TimerLayerMatterGoatStore) GetSessionsForChannel(channelId string) ([]*model.MGSession, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.GetSessionsForChannel(channelId)
	s.observe("GetSessionsForChannel", start, err)
	return result, err
}

func (s *TimerLayerMatterGoatStore) DeleteSession(id string) error {
	start := time.Now()
	err := s.MatterGoatStore.DeleteSession(id)
	s.observe("DeleteSession", start, err)
	return err
}

func (s *TimerLayerMatterGoatStore) SaveParticipant(participant *model.MGSessionParticipant) (*model.MGSessionParticipant, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.SaveParticipant(participant)
	s.observe("SaveParticipant", start, err)
	return result, err
}

func (s *TimerLayerMatterGoatStore) GetParticipantsForSession(sessionId string) ([]*model.MGSessionParticipant, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.GetParticipantsForSession(sessionId)
	s.observe("GetParticipantsForSession", start, err)
	return result, err
}

func (s *TimerLayerMatterGoatStore) DeleteParticipant(sessionId string, agentProfileId string) error {
	start := time.Now()
	err := s.MatterGoatStore.DeleteParticipant(sessionId, agentProfileId)
	s.observe("DeleteParticipant", start, err)
	return err
}

func (s *TimerLayerMatterGoatStore) SaveTurn(turn *model.MGTurn) (*model.MGTurn, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.SaveTurn(turn)
	s.observe("SaveTurn", start, err)
	return result, err
}

func (s *TimerLayerMatterGoatStore) UpdateTurn(turn *model.MGTurn) (*model.MGTurn, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.UpdateTurn(turn)
	s.observe("UpdateTurn", start, err)
	return result, err
}

func (s *TimerLayerMatterGoatStore) GetTurnsForSession(sessionId string) ([]*model.MGTurn, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.GetTurnsForSession(sessionId)
	s.observe("GetTurnsForSession", start, err)
	return result, err
}

func (s *TimerLayerMatterGoatStore) SaveApproval(approval *model.MGApproval) (*model.MGApproval, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.SaveApproval(approval)
	s.observe("SaveApproval", start, err)
	return result, err
}

func (s *TimerLayerMatterGoatStore) UpdateApproval(approval *model.MGApproval) (*model.MGApproval, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.UpdateApproval(approval)
	s.observe("UpdateApproval", start, err)
	return result, err
}

func (s *TimerLayerMatterGoatStore) GetApproval(id string) (*model.MGApproval, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.GetApproval(id)
	s.observe("GetApproval", start, err)
	return result, err
}

func (s *TimerLayerMatterGoatStore) GetApprovalsForSession(sessionId string) ([]*model.MGApproval, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.GetApprovalsForSession(sessionId)
	s.observe("GetApprovalsForSession", start, err)
	return result, err
}

func (s *TimerLayerMatterGoatStore) SaveMemoryProposal(proposal *model.MGMemoryProposal) (*model.MGMemoryProposal, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.SaveMemoryProposal(proposal)
	s.observe("SaveMemoryProposal", start, err)
	return result, err
}

func (s *TimerLayerMatterGoatStore) UpdateMemoryProposal(proposal *model.MGMemoryProposal) (*model.MGMemoryProposal, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.UpdateMemoryProposal(proposal)
	s.observe("UpdateMemoryProposal", start, err)
	return result, err
}

func (s *TimerLayerMatterGoatStore) GetMemoryProposalsForSession(sessionId string) ([]*model.MGMemoryProposal, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.GetMemoryProposalsForSession(sessionId)
	s.observe("GetMemoryProposalsForSession", start, err)
	return result, err
}

func (s *TimerLayerMatterGoatStore) SaveMarkdownExport(export *model.MGMarkdownExport) (*model.MGMarkdownExport, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.SaveMarkdownExport(export)
	s.observe("SaveMarkdownExport", start, err)
	return result, err
}

func (s *TimerLayerMatterGoatStore) GetMarkdownExportsForSession(sessionId string) ([]*model.MGMarkdownExport, error) {
	start := time.Now()
	result, err := s.MatterGoatStore.GetMarkdownExportsForSession(sessionId)
	s.observe("GetMarkdownExportsForSession", start, err)
	return result, err
}
